### ISSUE TITLE
[ENHANCEMENT] Show remaining time (relative) + end time (absolute) together

### ISSUE THREAD

**Issue by Eldenroot** [Snake-FW/P32-FW#8]
Please, before you create a new feature request, please make sure you searched in open and closed issues and couldn't find anything that matches.

Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]
**Optional upgrades** - Bondtech IFS, Wifi module

**Is your suggested improvement related to an existing problem? Please describe.**
  With internet connection you loose relative remaining time on print screen.

**Describe the expected functionality**
  It should display both values - something like Print ends: 08:15 (32 minutes left)...

**Comment by espr14** [comment]
This is too long but it could be in two rows.

**Comment by Eldenroot** [comment]
It was just an example... because my printer is connected to internet but with this I have lost the ability to use relative time... it sucks.

Maybe add a clock to the header?

**Comment by espr14** [comment]
Header would be more complicated. But do you need both or a switch in a menu is enough?

**Comment by espr14** [comment]
Fixed in 4.4.1.3
